import org.junit.Ignore
import org.junit.Test

import static Protein.protein

class ProteinTest {
  @Test void testMonoisotopicMass() {
    assert 0D == protein('').monoisotopicMass()
    assert 71.03711D == protein('A').monoisotopicMass()
    assert 821.392D == protein('SKADYEK').monoisotopicMass().round(3)
    assert PROTEIN_MASS1.mass == protein(PROTEIN_MASS1.protein).monoisotopicMass().round(3)
  }

  @Test void findMotif() {
    def nGlycosylationMotif = 'N(?!P).[ST](?!P).'
    assert PROTEIN_MOTIF_A2Z669.occurrences == Protein.parseFasta(PROTEIN_MOTIF_A2Z669.fasta)[0].findMotifs(nGlycosylationMotif)
    assert PROTEIN_MOTIF_B5ZC00.occurrences == Protein.parseFasta(PROTEIN_MOTIF_B5ZC00.fasta)[0].findMotifs(nGlycosylationMotif)
    assert PROTEIN_MOTIF_P07204_TRBM_HUMAN.occurrences == Protein.parseFasta(PROTEIN_MOTIF_P07204_TRBM_HUMAN.fasta)[0].findMotifs(nGlycosylationMotif)
    assert PROTEIN_MOTIF_P20840_SAG1_YEAST.occurrences == Protein.parseFasta(PROTEIN_MOTIF_P20840_SAG1_YEAST.fasta)[0].findMotifs(nGlycosylationMotif)
  }
  @Test @Ignore void findMotifFromUniprot() {
    def nGlycosylationMotif = 'N(?!P).[ST](?!P).'
    for (String id : ['P01044_KNH1_BOVIN', 'Q0SU18', 'P02186', 'Q05557', 'A6WKC3', 'P00743_FA10_BOVIN', 'P49286',
                      'B6J655', 'P27918_PROP_HUMAN', 'Q03745', 'Q67JS9', 'P08709_FA7_HUMAN', 'P01233_CGHB_HUMAN']) {
      String fastaUri = "http://www.uniprot.org/uniprot/${id}.fasta"
      String fasta = new URL(fastaUri).text
      def positions = Protein.parseFasta(fasta)[0].findMotifs(nGlycosylationMotif)
      if (positions) {
        println id
        println positions.join(' ')
      }
    }
  }

  static Map PROTEIN_MASS1 = [
      protein: 'IAAVFLWKMGPCKCWCTAGIEFWAAEENTWWFEKHMNNATYTDTARMFPMVPKFTCDIHVVFQLEFQGQIFEPGTPPPTNNMPERTVCIFRKPRTFIWQHIIAAFWFQELWWHWMFWWLVCASSSGCCCQNSTHKMVTFGATVIQMNARRNKGTIHITVGFEMANICDHKNVNISGYCPMIDVSQYKAFAGFQTNCKVRTYHMNEEMDDEHGPWYYNFQQAYCTGWGQKAELQEKISPDQVFWSRAQQKVQRDYHWNTRTHHKYWNEYYNKESHETDLKIIYFDSNIDTPAHKGYVPAPNGKEPNLCMCWGRGHNLSKLKAEHTMYQMNRNQYFPNNGGWSPGHVLRDGQILKGPHTHGEEAELPYDPGFRAMKQKADNRLSFYDLLWMLRHCGVPSPPVYSLTWAWSLFRMFCYYRHLYMKVCGDFLLEIALGRMERCISHRSWKSFLGVLFCQDRNQDILIHYNREHVSTIKRQHFFKVTSWGRTCPNVAIKVFCVLSFFSKMWWKSDYFLDEYKMGHKDTVITFNFMIDDRYVRQSLNSPDKDSKYKILKVVGPQQCVNKLYCEIADPWKFVLMTWYMRATGKVGMYEKFIHNYNSTYIICSKITRIQHPLEGYLSIQWPPTGHCQMTRCQFIIHPKYHEDHPMRERKEIDVIVDECLMLAQYEYMPFVAREAIFQQRCWVIMQDVNEGACMVPQGMNGSMKDMPLVAIYPHSCPKEVIHRRVNGGTLEDYHHLVHAIGYMYHVDGTFVDASYEGGIHTYYLTFNGIEYGVIPGLGHPHHAKSMQADSWKAKGPCTGFLNCWPLLEAVDSIGLKGRENVSKTEHFQKNMKGSRMDFFTYWVVFITIWPWCDYLRHMYRGWGLHANMPYDMKPHIIMMHMPPDCELYPMTDYRM',
      mass   : 105804.693D
  ]
//N(?!P).[ST](?!P).
  static Map PROTEIN_MOTIF_A2Z669 = [
      fasta      : '>sp|A2Z669|CSPLT_ORYSI CASP-like protein 5A2 OS=Oryza sativa subsp. indica GN=OsI_33147 PE=3 SV=1\n' +
          'MRASRPVVHPVEAPPPAALAVAAAAVAVEAGVGAGGGAAAHGGENAQPRGVRMKDPPGAP\n' +
          'GTPGGLGLRLVQAFFAAAALAVMASTDDFPSVSAFCYLVAAAILQCLWSLSLAVVDIYAL\n' +
          'LVKRSLRNPQAVCIFTIGDGITGTLTLGAACASAGITVLIGNDLNICANNHCASFETATA\n' +
          'MAFISWFALAPSCVLNFWSMASR',
      occurrences: []
  ]
  static Map PROTEIN_MOTIF_B5ZC00 = [
      fasta      : '>sp|B5ZC00|SYG_UREU1 Glycine--tRNA ligase OS=Ureaplasma urealyticum serovar 10 (strain ATCC 33699 / Western) GN=glyQS PE=3 SV=1\n' +
          'MKNKFKTQEELVNHLKTVGFVFANSEIYNGLANAWDYGPLGVLLKNNLKNLWWKEFVTKQ\n' +
          'KDVVGLDSAIILNPLVWKASGHLDNFSDPLIDCKNCKARYRADKLIESFDENIHIAENSS\n' +
          'NEEFAKVLNDYEISCPTCKQFNWTEIRHFNLMFKTYQGVIEDAKNVVYLRPETAQGIFVN\n' +
          'FKNVQRSMRLHLPFGIAQIGKSFRNEITPGNFIFRTREFEQMEIEFFLKEESAYDIFDKY\n' +
          'LNQIENWLVSACGLSLNNLRKHEHPKEELSHYSKKTIDFEYNFLHGFSELYGIAYRTNYD\n' +
          'LSVHMNLSKKDLTYFDEQTKEKYVPHVIEPSVGVERLLYAILTEATFIEKLENDDERILM\n' +
          'DLKYDLAPYKIAVMPLVNKLKDKAEEIYGKILDLNISATFDNSGSIGKRYRRQDAIGTIY\n' +
          'CLTIDFDSLDDQQDPSFTIRERNSMAQKRIKLSELPLYLNQKAHEDFQRQCQK',
      occurrences: [85, 118, 142, 306, 395]]
  static Map PROTEIN_MOTIF_P07204_TRBM_HUMAN = [
      fasta      : '>sp|P07204|TRBM_HUMAN Thrombomodulin OS=Homo sapiens GN=THBD PE=1 SV=2\n' +
          'MLGVLVLGALALAGLGFPAPAEPQPGGSQCVEHDCFALYPGPATFLNASQICDGLRGHLM\n' +
          'TVRSSVAADVISLLLNGDGGVGRRRLWIGLQLPPGCGDPKRLGPLRGFQWVTGDNNTSYS\n' +
          'RWARLDLNGAPLCGPLCVAVSAAEATVPSEPIWEEQQCEVKADGFLCEFHFPATCRPLAV\n' +
          'EPGAAAAAVSITYGTPFAARGADFQALPVGSSAAVAPLGLQLMCTAPPGAVQGHWAREAP\n' +
          'GAWDCSVENGGCEHACNAIPGAPRCQCPAGAALQADGRSCTASATQSCNDLCEHFCVPNP\n' +
          'DQPGSYSCMCETGYRLAADQHRCEDVDDCILEPSPCPQRCVNTQGGFECHCYPNYDLVDG\n' +
          'ECVEPVDPCFRANCEYQCQPLNQTSYLCVCAEGFAPIPHEPHRCQMFCNQTACPADCDPN\n' +
          'TQASCECPEGYILDDGFICTDIDECENGGFCSGVCHNLPGTFECICGPDSALARHIGTDC\n' +
          'DSGKVDGGDSGSGEPPPSPTPGSTLTPPAVGLVHSGLLIGISIASLCLVVALLALLCHLR\n' +
          'KKQGAARAKMEYKCAAPSKEVVLQHVRTERTPQRL',
      occurrences: [47, 115, 116, 382, 409]]
  static Map PROTEIN_MOTIF_P20840_SAG1_YEAST = [
      fasta      : '>sp|P20840|SAG1_YEAST Alpha-agglutinin OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) GN=SAG1 PE=1 SV=2\n' +
          'MFTFLKIILWLFSLALASAININDITFSNLEITPLTANKQPDQGWTATFDFSIADASSIR\n' +
          'EGDEFTLSMPHVYRIKLLNSSQTATISLADGTEAFKCYVSQQAAYLYENTTFTCTAQNDL\n' +
          'SSYNTIDGSITFSLNFSDGGSSYEYELENAKFFKSGPMLVKLGNQMSDVVNFDPAAFTEN\n' +
          'VFHSGRSTGYGSFESYHLGMYCPNGYFLGGTEKIDYDSSNNNVDLDCSSVQVYSSNDFND\n' +
          'WWFPQSYNDTNADVTCFGSNLWITLDEKLYDGEMLWVNALQSLPANVNTIDHALEFQYTC\n' +
          'LDTIANTTYATQFSTTREFIVYQGRNLGTASAKSSFISTTTTDLTSINTSAYSTGSISTV\n' +
          'ETGNRTTSEVISHVVTTSTKLSPTATTSLTIAQTSIYSTDSNITVGTDIHTTSEVISDVE\n' +
          'TISRETASTVVAAPTSTTGWTGAMNTYISQFTSSSFATINSTPIISSSAVFETSDASIVN\n' +
          'VHTENITNTAAVPSEEPTFVNATRNSLNSFCSSKQPSSPSSYTSSPLVSSLSVSKTLLST\n' +
          'SFTPSVPTSNTYIKTKNTGYFEHTALTTSSVGLNSFSETAVSSQGTKIDTFLVSSLIAYP\n' +
          'SSASGSQLSGIQQNFTSTSLMISTYEGKASIFFSAELGSIIFLLLSYLLF',
      occurrences: [79, 109, 135, 248, 306, 348, 364, 402, 485, 501, 614]]
}
