import org.junit.Test

import static Protein.protein

class ProteinTest extends GroovyTestCase {
  @Test void testMonoisotopicMass() {
    assert 0D == protein('').monoisotopicMass()
    assert 71.03711D == protein('A').monoisotopicMass()
    assert 821.392D == protein('SKADYEK').monoisotopicMass().round(3)
    assert PROTEIN_MASS1.mass == protein(PROTEIN_MASS1.protein).monoisotopicMass().round(3)
  }

  static Map PROTEIN_MASS1 = [
      protein: 'IAAVFLWKMGPCKCWCTAGIEFWAAEENTWWFEKHMNNATYTDTARMFPMVPKFTCDIHVVFQLEFQGQIFEPGTPPPTNNMPERTVCIFRKPRTFIWQHIIAAFWFQELWWHWMFWWLVCASSSGCCCQNSTHKMVTFGATVIQMNARRNKGTIHITVGFEMANICDHKNVNISGYCPMIDVSQYKAFAGFQTNCKVRTYHMNEEMDDEHGPWYYNFQQAYCTGWGQKAELQEKISPDQVFWSRAQQKVQRDYHWNTRTHHKYWNEYYNKESHETDLKIIYFDSNIDTPAHKGYVPAPNGKEPNLCMCWGRGHNLSKLKAEHTMYQMNRNQYFPNNGGWSPGHVLRDGQILKGPHTHGEEAELPYDPGFRAMKQKADNRLSFYDLLWMLRHCGVPSPPVYSLTWAWSLFRMFCYYRHLYMKVCGDFLLEIALGRMERCISHRSWKSFLGVLFCQDRNQDILIHYNREHVSTIKRQHFFKVTSWGRTCPNVAIKVFCVLSFFSKMWWKSDYFLDEYKMGHKDTVITFNFMIDDRYVRQSLNSPDKDSKYKILKVVGPQQCVNKLYCEIADPWKFVLMTWYMRATGKVGMYEKFIHNYNSTYIICSKITRIQHPLEGYLSIQWPPTGHCQMTRCQFIIHPKYHEDHPMRERKEIDVIVDECLMLAQYEYMPFVAREAIFQQRCWVIMQDVNEGACMVPQGMNGSMKDMPLVAIYPHSCPKEVIHRRVNGGTLEDYHHLVHAIGYMYHVDGTFVDASYEGGIHTYYLTFNGIEYGVIPGLGHPHHAKSMQADSWKAKGPCTGFLNCWPLLEAVDSIGLKGRENVSKTEHFQKNMKGSRMDFFTYWVVFITIWPWCDYLRHMYRGWGLHANMPYDMKPHIIMMHMPPDCELYPMTDYRM',
      mass   : 105804.693D
  ]
}
