import groovy.transform.CompileStatic

@CompileStatic
class NumberOfNucleotides {
  public static void main(String ... args) {
    String strand = "ACATTCATTTAACGTGTAGATTCGTTTATCATCGAGCTCAGCTTCCACTACGACTGCTAGAGGGTCATGCACTCCCCGTCCATTCCGAGAGGCTTGCGGACGTTGGCCGACGGAAGATCAATGCGTATCATTTCAGTTTTGAATGACGGCCCCAGTGAACCCCCAATACTCTCAATTAAAACTCCTTTAATCTGAGTAGGCTGCCCACTTACCAGATCTTAATTACTGATATACCAGCTCGCCTATTGTTCAATTGGAACGATATTTCCACGCTACGGGACGCCACGCACGCAAATTCTCCTCGGCAGGGCCTGGGCACTAATGGCCTATTAAGAATTCCACTAGCCAATTATATCTGCACTGTTCAGTAGTTGAGAGACCCAGGCCACGGAGCCTACCGTCGCGACCATACCGGGTTTTCATGGTAATAAGGTCACATGTTTACTGACCAATTACTCTAGCCAATTCAGCTGGGGCCACAACTTTACGACGCTCGTGGCTTGGAGACTAATGAAAGTGAGTAAACCCTCCGAATCTTCACAAGTTGTCGCGGCGTCATAAATCTGCGTGTGTCCCTTAATCCAAAGGGGCCTACGATATTTACTGTTCCGCATGCTTAAAATTGTCAGGCCCATCTACTACAGCTCTACCATTCTAGGCCATGCCGGTCCCATCGGCGCGTCCAATAACCCTTCAAGTCCCCGGATTACCGTTCTTGGCTTCCCAATGTCGTATGGATACTTGCACCTAATGGAATGACATGGCAGCGATCCTCGAATTGGACACCCGTCGAGTCCCAGGTTACCAAGATTCAACCTCGTATATCACACTATTGTAGTGTTAGTT";
    print "${getNOfOccurrences(strand, 'A' as char)} ${getNOfOccurrences(strand, 'C' as char)} " +
        "${getNOfOccurrences(strand, 'G' as char)} ${getNOfOccurrences(strand, 'T' as char)}"
  }
  static int getNOfOccurrences(String strand, char nucleotide) {
    int result = 0
    for (int i = 0; i < strand.length(); i++) {
      if (strand.charAt(i) == nucleotide) {
        result++
      }
    }
    return result
  }
}
